- .gitmodules
close #26 
- application 설정을 위한 서브모듈을 도입하였습니다
> [BE] applicaiton 설정 서브모듈 도입

- client/src/shared/components/IconButton/IconButton.stories.tsx
- client/src/shared/components/IconButton/IconButton.styled.ts
- client/src/shared/components/IconButton/IconButton.tsx
- client/src/shared/components/IconButton/index.ts
close #22
- IconButton 컴포넌트 구현했습니다. 
- button의 타입을 기본 `type` 속성을 `button`으로 강제했어요.
- hover시 전달받은 color 값에 기반으로 배경색이 적용되도록 설정했습니다.
> [FE] IconButton 컴포넌트, 스토리북 구현

- client/src/shared/components/ProgressBar/ProgressBar.stories.tsx
- client/src/shared/components/ProgressBar/ProgressBar.styled.ts
- client/src/shared/components/ProgressBar/ProgressBar.tsx
- client/src/shared/components/ProgressBar/index.ts
close #34 
- ProgressBar UI 컴포넌트 구현
- 진행률(value / max)에 따라 바 너비 조절
- 색상, 높이, border-radius, 애니메이션 여부 등 커스터마이징 가능
- 접근성을 고려한 aria-label 적용
https://github.com/user-attachments/assets/3f5c49b2-2014-4beb-b454-c972842e4d7b
```tsx
<ProgressBar value={60} />
<ProgressBar
value={75}
height="12px"
color="#4caf50"
backgroundColor="#e0e0e0"
borderRadius="0px"
/>
<ProgressBar value={90} max={100} animated={false} />
```
> [FE] ProgressBar 컴포넌트, 스토리북 구현

- client/eslint.config.js
- client/package.json
- client/pnpm-lock.yaml
- client/src/api/ClientQueryProvider.tsx
- client/src/api/fetcher.ts
- client/src/main.tsx
close #103
- 패칭/서버 상태 관리 라이브러리 설정했습니다.
> [FE] 패칭/서버 상태 관리 라이브러리 설정

- server/src/main/java/com/ahmadda/presentation/config/WebMvcConfig.java
- server/src/main/resources/application-dev.yml
close #127
- 개발 환경에서 사용할 CORS 설정 추가
- 현업 개발의 편의성을 위해 모든 Path, Origin, Method 등등.. 에 대해 요청을 허용했습니다!! 
- 저희의 정신건강을 위해..!
> [BE] 개발 환경용 CORS 설정 추가

- server/Dockerfile
- server/src/main/resources/application-dev.yml
- server/src/main/resources/application.yml
close #134 
- 배포 과정에서 사용할 Dockerfile 추가
- 개발 환경 설정 파일 추가
- 멀티스테이지 빌드나 알파인 기반 이미지 적용 등 Docker 최적화는 추후에 진행해봅시다~~ 
- 개발 서버에서는 H2가 아닌 MySQL(RDS) 를 사용하도록 설정했습니다.
- 이를 위해 RDS를 직접 배포 및 연결 완료했습니다!
> [BE] 배포용 Dockerfile 추가

- client/package.json
- client/pnpm-lock.yaml
- client/webpack.config.cjs
close #139 
- webpack dotenv 설정했습니다.
> [FE] webpack dotenv 설정

- .github/workflows/validation-opened-prs.yml
> [BE] CI 스크립트 작성

- client/src/features/Event/New/components/EventCreateForm.tsx
- client/src/features/Event/New/components/QuestionForm.tsx
- client/src/features/Event/New/components/QuestionItem.tsx
close #145 
- 질문 작성 폼 퍼블리싱 완료했습니다.
- 생성/삭제는 임의로 구현 진행했습니다.
> [FE] 이벤트 생성 페이지 질문 작성 폼 퍼블리싱

- client/buildspec.yml
close #171
- 코드 파이프라인을 통한 CD 연결을 위해 buildspec.yml 파일을 작성했습니다.
> [FE] cd를 위한 buildspec.yml 작성

- client/buildspec.yml
- client/src/__test__/testing.test.tsx
close #176
- CodeBuild 환경에는 기본적으로 npm만 설치되어 있고, pnpm은 없다고 합니다. 따라서 글로벌로 pnpm install 하는 스크립트 추가했습니다.
> [FE] build 스크립트 수정

- client/src/api/queries/my.ts
close #189 
- 투다께서 내가 주최한/참여한 이벤트 GET api의 주소가 변경되었다고 합니다.
- 고정된 값을 제거하면서 변했다고 하여 반영했습니다!
> [FE] 내가 주최한/참여한 이벤트 GET api url 변경

- .github/workflows/close-linked-issues.yml
- .github/workflows/dev-deploy-closed-prs.yml
- .github/workflows/validation-opened-prs.yml
close #203 
- 이름이 지정되지 않은 workflow 파일에 이름 추가
- Docker 멀티 플랫폼 빌드 속도 개선 시도
- 워크플로 이름이 지정되어 있지 않아 어떤 작업인지 식별하기 어려운 문제가 있어 이름을 명시했어요~~ (데모데이 때 당황 좀 했기에..)
- 기존 배포 자동화 워크플로의 총 실행 시간 약 10분 중, Docker 이미지 빌드에 약 7분이 소요되고 있습니다 ㅠㅠ 
- 멀티 플랫폼 빌드로 인해 빌드 시간이 길어진 것으로 추정되며, 이를 개선하기 위해 GitHub Actions의 러너를 `ubuntu-22.04-arm` 등 ARM 기반으로 변경하여 빌드 성능을 개선해보겠습니다!! 이번에 무료로 제공된다고 해서.. ㅎ
- https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> [BE] 워크플로 이름 명시 및 멀티 플랫폼 빌드 속도 개선

- server/src/main/java/com/ahmadda/application/LoginService.java
- server/src/main/java/com/ahmadda/infra/jwt/JwtTokenProvider.java
- server/src/main/java/com/ahmadda/infra/oauth/GoogleOAuthProvider.java
- server/src/main/java/com/ahmadda/presentation/LoginController.java
- server/src/main/java/com/ahmadda/presentation/dto/LoginRequest.java
- server/src/main/resources/application-dev.yml
- server/src/main/resources/application-local.yml
- server/src/main/resources/application.yml
- server/src/test/java/com/ahmadda/application/LoginServiceTest.java
close #206 
로그인 시 프론트로 부터 받아온 redirectUri를 사용하도록 수정하였습니다. 
*** 프론트에서 유효한 redirectUri를 제공하지 않으면 올바르게 작동하지 않습니다. ***
*** 테스트 코드 올바르게 작동하는지 확인 했습니다 ***
> [BE] redirectUri를 프론트로 부터 받아도록 개선

- client/pnpm-lock.yaml
close #219 
- node 버전 다운그레이드 및 절대 경로 문제 해결했습니당
- 도움주셔서 감사합니당 !!
> [FE] node 버전 다운그레이드 및 절대 경로 문제 해결

- server/src/main/java/com/ahmadda/presentation/EventGuestController.java
- server/src/main/java/com/ahmadda/presentation/EventNotificationController.java
- server/src/main/java/com/ahmadda/presentation/MemberController.java
- server/src/main/java/com/ahmadda/presentation/OrganizationMemberController.java
close #218
- 자신의 프로필 조회 기능에 대한 스웨거 문서 정리
- 자신의 조직원 프로필 조회 기능에 대한 스웨거 문서 정리
- 이벤트 게스트 조회 기능에 대한 스웨거 문서 정리
- 이벤트 알림 발송 기능에 대한 스웨거 문서 정리
클라이언트분들과 Swagger 명세 작성 기준에 대해 논의한 결과를 반영하여 작성했습니다!!
제가 먼저 코드로 정리해두었으니, 이후 작업하시는 분들도 참고해서 작성해주시면 감사하겠습니다 🙏
> [BE] 자신의 프로필 조회, 자신의 조직원 프로필 조회, 이벤트 게스트 조회,이벤트 알림 스웨거 세팅 

- server/src/main/java/com/ahmadda/infra/oauth/GoogleOAuthProvider.java
- server/src/main/java/com/ahmadda/presentation/LoginController.java
close #224 
- 로그인 API 스웨거 추가하였습니다.
> [BE] 로그인 API 설명 스웨거 추가

- server/src/main/java/com/ahmadda/presentation/EventGuestController.java
- server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
close #223 
다음 API를 스웨거로 문서화 했습니다. 
- 이벤트 생성 API 스웨거 작성 
- 이벤트 상세 조회 API 스웨거 작성 
- 이벤트 참여 API 스웨거 작성 
- 이벤트 게스트 여부 API 스웨거 작성
> [BE] 이벤트 및 조직 도메인 API Swagger 문서화

- server/build.gradle
- server/src/main/java/com/ahmadda/presentation/config/CorsProperties.java
- server/src/main/java/com/ahmadda/presentation/config/WebMvcConfig.java
- server/src/main/resources/application-dev.yml
- server/src/main/resources/application-local.yml
- server/src/main/resources/application-prod.yml
- server/src/main/resources/application.yml
close #236
- 운영 환경용 CORS 설정 추가
- 운영 환경 전용 설정 파일 작성
- 헬스 체크 API 추가 (Spring Actuator 사용)
곧 모니터링 기능 구현을 위해 필요한 요구사항이기도 하여, 
헬스 체크 API를 위해 Spring Actuator를 사용했습니다~~
보안 및 운영 측면에서 Actuator 사용 시 주의할 점은 아래 글들이 많은 도움이 되었어요!  
처음 접하시는 분이라면 읽어보시는 것을 추천드립니다~~ 👍 
- [우아한형제들 - Spring Boot Actuator 보안 이슈](https://techblog.woowahan.com/9232/)
- [토스 - Actuator로 인한 장애 사례와 대응 방법](https://toss.tech/article/how-to-work-health-check-in-spring-boot-actuator)
> [BE] 운영 환경 세팅

- server/src/main/java/com/ahmadda/domain/Event.java
- server/src/test/java/com/ahmadda/application/EventGuestServiceTest.java
- server/src/test/java/com/ahmadda/domain/EventTest.java
close #279 
[이전 PR](https://github.com/woowacourse-teams/2025-ah-madda/pull/267) 에서 hasGuest 메서드에서 주최자인 경우에 true로 리턴을 해야하는데 false로 리턴을 해버려 다시 고쳤습니다..!
> [BE] 주최자일 경우 게스트 여부 true로 변경

- server/src/main/java/com/ahmadda/infra/slack/config/SlackReminderConfig.java
- server/src/main/resources/application.yml
close #281 
- SlackReminderConfig에서 SlackAlarmProperties을 활성화해주었습니다.
- application.yml 파일에서 slack.yml 파일 import 해주었습니다.
> [BE] Slack 프로퍼티 활성화 및 slack.yml import 추가

- server/src/main/java/com/ahmadda/presentation/OrganizationEventController.java
close #331 
주최자 여부 스웨거 명세를 확인하던 중 array 응답으로 되어 있어 이부분을 고쳤습니다. 
복붙하면 안되겠다.. ㅎ
> [BE] 주최자 여부 API 스웨거 명세 수정

- .github/workflows/dev-deploy-closed-prs.yml
- .github/workflows/prod-deploy-on-release.yml
- server/src/main/java/com/ahmadda/domain/OrganizationMember.java
close #374
- self-hosted runner가 2대가 되면서 배포 job 실행 대상이 불안정해지는 현상 확인
- 배포는 반드시 지정된 runner에서 실행되어야 하므로 해당 runner에 레이블 지정
- runs-on 설정을 통해 배포 Job이 명확히 해당 runner에서만 실행되도록 수정
제발 ㅠㅠ
> [BE] 간혈적으로 배포 자동화가 실패하는 오류 해결

- .github/workflows/dev-deploy-closed-prs.yml
- .github/workflows/prod-deploy-on-release.yml
close #409 
log 볼륨 설정 prod에서 활성화 및 dev에서 제거 했습니다.
> [BE] log 볼륨 설정 prod에서 활성화 및 dev에서 제거

- server/src/main/resources/application-dev.yml
close #564
- Staging 환경에서 클라이언트 도메인을 허용하도록 CORS 설정 수정
> [BE] 클라이언트 Staging 환경 대응을 위한 CORS 설정 변경

- server/src/main/resources/application-local.yml
close #592 
http://local.ahmadda.com:5173 cors 허용
> [BE] http://local.ahmadda.com:5173 cors 허용

- server/src/main/java/com/ahmadda/application/EventGuestService.java
- server/src/main/java/com/ahmadda/application/EventNotificationOptOutService.java
- server/src/main/java/com/ahmadda/application/EventNotificationService.java
- server/src/main/java/com/ahmadda/application/EventService.java
- server/src/main/java/com/ahmadda/application/EventStatisticService.java
- server/src/main/java/com/ahmadda/application/EventTemplateService.java
- server/src/main/java/com/ahmadda/application/MemberService.java
- server/src/main/java/com/ahmadda/application/OrganizationGroupService.java
- server/src/main/java/com/ahmadda/application/OrganizationInviteCodeService.java
- server/src/main/java/com/ahmadda/application/OrganizationMemberService.java
- server/src/main/java/com/ahmadda/application/OrganizationService.java
- server/src/main/java/com/ahmadda/application/ReminderHistoryService.java
- server/src/main/java/com/ahmadda/infra/database/DataSourceConfig.java
- server/src/main/java/com/ahmadda/infra/database/ReplicationRoutingDataSource.java
- server/src/main/resources/application-prod.yml
> [RELEASE] v4
